config/routes.rb
Rails.application.routes.draw do
  root 'documents#index'
  
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/profile' => 'users#show', :as => :user 
  get '/profile/edit' => 'users#edit'
  patch '/profile' => 'users#update'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :documents, except: [:new, :edit]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
    belongs_to :user
    has_one_attached :file
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :documents
    validates :user_name, :full_name, :email, presence: true
    validates :user_name, length: { maximum: 15 }, uniqueness: true
    validates :password, presence: true, length: { minimum: 8, maximum: 15 },format: { 
        with: /(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).*/, 
        message:  "Password must contain atleast one uppercase, lowercase and number" 
    }, on: :create
end

app/controllers/application_controller.rb
include ActionView::Helpers::NumberHelper

class ApplicationController < ActionController::Base
    helper_method :current_user, :get_file_size

    def current_user
        @current_user = User.find(session[:user_id]) if session[:user_id] 
    end

    def require_user
        redirect_to '/login' unless current_user
    end

    def get_file_size(byte)
        number_to_human_size(byte)
    end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
    before_action :require_user, except: [:show]

    def index 
        @documents = current_user.documents.order(created_at: :desc)
    end

    def create
        file_to_upload = current_user.documents.create(file_params)
        file_to_upload.filename = file_params["file"].original_filename
        file_to_upload.save
        redirect_to root_path
    end

    def show
        @document = Document.find_by(key: params[:id], shared: true)
        @user = User.find(@document[:user_id]) if @document
    end

    def destroy
        @document = current_user.documents.find_by!(key: params[:id])
        @document && @document.file.purge_later
        @document && @document.destroy
        redirect_to root_path
    end

    def update
        @checked = (params[:document] && (params[:document][:shared] == '1')) ? true : false
        @document = current_user.documents.find_by!(key: params[:id])
        @document && @document.update(shared: @checked) 
        redirect_to root_path
    end

    private
    def file_params
        params.require(:document).permit(:file).merge(key: "#{Time.now.to_i}")
    end

end

app/controllers/files_controller.rb
class FilesController < ApplicationController
    before_action :require_user, except: [:show]

    def index 
        @documents = current_user.documents.order(created_at: :desc)
    end

    def create
        
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        is_session_present = session[:user_id]
        if is_session_present && User.find_by_id(session[:user_id])
            redirect_to root_path
        end
    end

    def create
        @params = params[:session]
        if @params 
            user_name = @params[:user_name]
            @user = User.find_by(user_name: user_name) if user_name
            if @user && @user.authenticate(@params[:password])
                session[:user_id] = @user.id
                redirect_to root_path
            else
                render :new
            end
        else
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to '/login'
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        if session[:user_id]
            redirect_to '/login' if User.find(session[:user_id])
        else
            @user = User.new
        end
    end

    def create
        @user = User.new(user_params)
        user_name = user_params['user_name'];
        email = user_params['email'];
        @is_user_name_present = User.exists?(user_name: user_name)
        @is_user_email_present = User.exists?(email: email)
        
        if @is_user_name_already_present || @is_user_email_already_present 
            render :new and return
        end

        if @user.save 
            session[:user_id] = @user.id
            @is_user_name_present = false;
            @is_user_email_present = false;
            redirect_to '/login'
        else
            render :new
        end
    end

    def show
        @user = current_user
    end

    def edit
        @user = current_user
    end

    def update
        @user = User.find(session[:user_id])
        @is_user_email_present = User.exists?(email: user_params['email'])        
        
        if @is_user_email_present 
            render :edit and return
        end

        if @user.update(user_params)
            @has_updated_profile = true
            render :show
        else
            render :edit
        end
    end
 
    private
    def user_params
        params.require(:user).permit(:user_name, :full_name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/documents/index.html.erb
<div style="margin: 16px;">
    <div style="display:flex; justify-content: space-between;">
        <div style="display:flex;">
            <h2> File Dashboard - &nbsp;</h2>
            <% if @documents && @documents.any? %>
                <% if @documents.count == 1%>
                    <h2> 1 File </h2>
                <% else %>
                    <h2><% @documents.count %> Files</h2>
                <% end%>
            <% else %>
               <h2>  No Files Found </h2>
            <% end %>
        </div>

        <div>
            <%= form_for(:document, url: documents_path, method: 'post') do |f| %>
                <%= f.label :file %> Upload
                <%= f.file_field :file , onchange: "this.form.submit();"%>
            <% end %>
        </div>
    </div>
    <% if @documents.any? %>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Upload Date</th>
                            <th>Actions</th>
                            <th>Size</th>
                            <th>Sharing</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @documents.each do |document| %>
                               <% if document.file.attached? %>
                                 <tr>
                                    <td><%= document.file.record.filename %></td>
                                    <td><%= document.file.record.created_at.strftime("%-d %b %Y %H:%M") %></td>
                                    <td>
                                        <%= link_to 'Download', document.file, download: '' %> |&nbsp;
                                        <%= link_to "Delete", document_path(document.key),
                                            data: {:confirm => 'Are you sure you want to delete?'}, 
                                            method: :delete %>
                                    </td>
                                     <td><%= get_file_size document.file.byte_size %></td>
                                    <td>
                                        <div style="display:flex;">
                                            <%= form_for(:document, url: document_path(document.key), 
                                                method: 'patch') do |f| %>
                                                <div class="custom-control custom-switch">
                                                    <input class="custom-control-input" type="checkbox" 
                                                        onclick="this.form.submit();" value="1" <%= 'checked' if document.shared %>
                                                        name="document[shared]" id="share-<%= document.key %>"/>
                                                    <label class="custom-control-label" 
                                                        for="share-<%= document.key %>"></label>
                                                </div>
                                            <% end %>
                                           <div>
                                                <% if document.shared %>
                                                    <%= link_to "Link", document_path(document.key), target: :_blank %>
                                                <% end %>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                               <% end %>
                        <% end %>
                    </tbody>
                </table>
            <% end %>
    
</div>

app/views/documents/show.html.erb
    <div style="margin: 16px;">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-8">
                        <h2>
                            <% if @user %>
                                Shared file from <b><%= @user.full_name %></b> (<b><%= @user.user_name%></b>)
                            <% else %>
                                File not available
                            <% end %>
                        </h2>
                    </div>
                </div>
            </div>
            <% if @document %>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Upload Date</th>
                            <th>Size</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><%= @document.file.record.filename %></td>
                            <td><%= @document.file.record.created_at.strftime("%-d %b %Y %H:%M") %></td>
                            <td><%= get_file_size @document.file.byte_size %></td>                            
                            <td>
                                <%= link_to 'Download', @document.file, download: '' %>
                            </td>
                        </tr>     
                    </tbody>
                </table>
            <% end %>
        </div>
    </div>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>File Share</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:#87cefa;">
    <nav class="navbar navbar-light bg-light">
      <%= link_to(root_path) do %>
        <b class="navbar-brand">File Sharing 101</b>
      <% end %>
      <div class="navbar-right">
        <% if current_user %> 
          <%= link_to current_user.full_name, '/profile', :style => 'text-decoration:none; color:black;'   %>
          &nbsp;
          <%= link_to "Log out", logout_path, method: "delete", :style => 'text-decoration:none;'  %>
        <% else %> 
           <%= link_to "Login", 'login', :style => 'text-decoration:none;' %>
           &nbsp;
           <%= link_to "Sign Up", 'signup', :style => 'text-decoration:none;' %>
        <% end %> 
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div style="display:flex; align-items:center;justify-content:center;">
    <div class="card" style="width: 24rem; padding: 1rem; margin-top: 2rem; border-radius: 8px;">
        <%= form_for(@user, url: user_path, method: 'patch') do |f| %>
            <h2>Edit Profile - <%= @user.user_name %></h2>
            <hr>
            <div class="form-group">
                <%= f.label :full_name, 'Full Name' %>
                <%= f.text_field :full_name, required: true %>
            </div>
            <div class="form-group">
                <%= f.label :email, 'Email Address' %>
                <%= f.email_field :email, 
                    required: true, 
                    pattern: "^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$" ,
                    title: 'Please enter valid email' 
                %> 
                <% if @is_user_email_present %>
                    <div class="form-message">
                    <small class="text-danger">Email already exists</small>
                    </div>
                <% end %> 
            </div>
            <div class="form-group">
                <%= f.submit "Save", class: 'btn btn-primary btn-block' %>
            </div>
        <% end %>
    </div>

</div>

app/views/users/new.html.erb
<div style="display:flex; align-items:center;justify-content:center;">
<div class="card" style="width: 24rem; padding: 1rem; margin-top: 2rem; border-radius: 8px;">
    <%= form_for(@user, url: '/signup', method: 'post') do |f| %>
		<h2>Sign Up</h2>
		<hr>
        <div class="form-group">
            <%= f.label :user_name, 'Username' %>
            <%= f.text_field :user_name, class: "form-control", 
                required: true, maxlength: 15 %>
            <% if @is_user_name_present %>
                <div class="form-message">
                    <small class="text-danger">User name already exists</small>
                </div>
            <% end %>  
        </div>
         
        <div class="form-group">
            <%= f.label :full_name, 'Full Name' %>
            <%= f.text_field :full_name, class: "form-control", 
                required: true %>
        </div>
        <div class="form-group">
            <%= f.label :email, 'Email Address' %>
            <%= f.email_field :email, class: "form-control", 
                required: true, 
                pattern: "^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$" ,
                title: 'Please enter valid email'
            %>
             <% if @is_user_email_present %>
                <div class="form-message">
                    <small class="text-danger">Email already exists</small>
                </div>
            <% end %>  
        </div>
		<div class="form-group">
            <%= f.label :password, 'Password' %>
            <%= f.password_field :password, 
                class: "form-control", 
                required: true, minlength: 8, maxlength: 15,
                pattern: '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).*',
                title: 'Password must contain atleast one uppercase, lowercase and number'
            %>
        </div>
		<div class="form-group">
            <%= f.submit "Create Account", class: 'btn btn-primary btn-block' %>
        </div>
    <% end %>
	<div class="text-center">Already have an account? <%= link_to "Login here", 'login', :style => 'text-decoration:none;' %></div>
</div>
</div>

app/views/users/show.html.erb
<div style="display:flex; align-items:center;justify-content:center;">
    <div class="card" style="width: 24rem; padding: 1rem; margin-top: 2rem; border-radius: 8px;">
        <form>
        <h2>User Profile - <%= @user.user_name %></h2>
            <hr>
            <div class="form-group">
                <label>Full Name</label>
                <input type="text" class="form-control" disabled value="<%= @user.full_name %>">
            </div>
            <div class="form-group">
                <label>Email Address</label>
                <input type="text" class="form-control" disabled value="<%= @user.email %>">
            </div>
            <div class="form-group">
                <%= link_to '/profile/edit', :style => 'text-decoration:none;' do %>
                    <button class="btn btn-primary btn-block">
                        Edit Profile
                    </button>
                <% end %>
            </div>
            <% if @has_updated_profile %> 
                <div>
                    <small class="text-success">Profile updated successfully!</small>
                </div>
            <% end %>
        </form>
    </div>
</div>